import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:sfcapp/models/contact_log_model.dart';
import 'package:sfcapp/services/audit_service.dart';

/// Service for managing tenant contact logs
class ContactLogService {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static final FirebaseAuth _auth = FirebaseAuth.instance;

  /// Create a contact log entry
  static Future<ContactLog> createContactLog({
    required String tenantId,
    required String facilityId,
    required ContactLogType type,
    required ContactLogDirection direction,
    String? subject,
    String? message,
    String? contactMethod,
    DateTime? contactDate,
    bool isAutoGenerated = false,
    String? relatedEntityId,
    String? relatedEntityType,
    Map<String, dynamic>? metadata,
  }) async {
    try {
      final user = _auth.currentUser;
      if (user == null) throw Exception('User not authenticated');

      if (kDebugMode) {
        print('🔄 [ContactLog] Creating contact log for tenant: $tenantId');
      }

      final now = DateTime.now();
      final log = ContactLog(
        id: '', // Will be set by Firestore
        tenantId: tenantId,
        facilityId: facilityId,
        type: type,
        direction: direction,
        subject: subject,
        message: message,
        contactMethod: contactMethod,
        contactDate: contactDate ?? now,
        contactedBy: user.uid,
        contactedByName: user.displayName ?? user.email,
        isAutoGenerated: isAutoGenerated,
        relatedEntityId: relatedEntityId,
        relatedEntityType: relatedEntityType,
        metadata: metadata,
        createdAt: now,
      );

      final ref = _firestore
          .collection('facilities')
          .doc(facilityId)
          .collection('tenants')
          .doc(tenantId)
          .collection('contactLogs')
          .doc();

      await ref.set(log.copyWith(id: ref.id).toFirestore());

      final createdLog = log.copyWith(id: ref.id);

      // Audit log (only for manual entries)
      if (!isAutoGenerated) {
        await AuditService.logContactLogCreated(
          facilityId: facilityId,
          tenantId: tenantId,
          logId: ref.id,
          type: type.name,
        );
      }

      if (kDebugMode) {
        print('✅ [ContactLog] Created contact log: ${ref.id}');
      }

      return createdLog;
    } catch (e) {
      if (kDebugMode) {
        print('❌ [ContactLog] Error creating contact log: $e');
      }
      rethrow;
    }
  }

  /// Auto-create contact log from communication (email/SMS)
  static Future<void> autoCreateFromCommunication({
    required String tenantId,
    required String facilityId,
    required ContactLogType type, // email or sms
    required String subject,
    String? message,
    String? contactMethod,
    String? relatedEntityId,
    String? relatedEntityType,
    Map<String, dynamic>? metadata,
  }) async {
    try {
      await createContactLog(
        tenantId: tenantId,
        facilityId: facilityId,
        type: type,
        direction: ContactLogDirection.outbound,
        subject: subject,
        message: message,
        contactMethod: contactMethod,
        isAutoGenerated: true,
        relatedEntityId: relatedEntityId,
        relatedEntityType: relatedEntityType,
        metadata: metadata,
      );

      if (kDebugMode) {
        print('✅ [ContactLog] Auto-created log from communication');
      }
    } catch (e) {
      if (kDebugMode) {
        print('⚠️ [ContactLog] Could not auto-create log: $e');
      }
      // Don't throw - contact log creation should not break communication
    }
  }

  /// Get contact logs for a tenant (real-time stream)
  static Stream<List<ContactLog>> getContactLogStream({
    required String tenantId,
    required String facilityId,
    int? limit,
  }) {
    try {
      final user = _auth.currentUser;
      if (user == null) {
        throw Exception('Not signed in');
      }

      if (kDebugMode) {
        print('🔄 [ContactLog] Setting up contact log stream for tenant: $tenantId');
      }

      Query query = _firestore
          .collection('facilities')
          .doc(facilityId)
          .collection('tenants')
          .doc(tenantId)
          .collection('contactLogs');

      // Try ordered query, fall back to unordered if index is building
      try {
        query = query.orderBy('contactDate', descending: true);
      } catch (e) {
        if (kDebugMode) {
          print('⚠️ [ContactLog] Ordered query not available, using unordered: $e');
        }
      }

      if (limit != null) {
        query = query.limit(limit);
      }

      return query.snapshots().map((snapshot) {
        final logs = snapshot.docs
            .map((doc) => ContactLog.fromFirestore(doc))
            .toList();

        // Sort in memory if we used fallback query
        logs.sort((a, b) => b.contactDate.compareTo(a.contactDate));

        if (kDebugMode) {
          print('📡 [ContactLog] Stream update: ${logs.length} logs for tenant: $tenantId');
        }

        return logs;
      });
    } catch (e) {
      if (kDebugMode) {
        print('❌ [ContactLog] Error setting up contact log stream: $e');
      }
      rethrow;
    }
  }

  /// Get contact logs for a tenant (one-time)
  static Future<List<ContactLog>> getContactLogs({
    required String tenantId,
    required String facilityId,
    int? limit,
  }) async {
    try {
      final user = _auth.currentUser;
      if (user == null) throw Exception('User not authenticated');

      if (kDebugMode) {
        print('🔄 [ContactLog] Getting contact logs for tenant: $tenantId');
      }

      Query query = _firestore
          .collection('facilities')
          .doc(facilityId)
          .collection('tenants')
          .doc(tenantId)
          .collection('contactLogs');

      // Try ordered query, fall back to unordered if index is building
      try {
        query = query.orderBy('contactDate', descending: true);
      } catch (e) {
        if (kDebugMode) {
          print('⚠️ [ContactLog] Ordered query not available, using unordered: $e');
        }
      }

      if (limit != null) {
        query = query.limit(limit);
      }

      final snapshot = await query.get();

      final logs = snapshot.docs
          .map((doc) => ContactLog.fromFirestore(doc))
          .toList();

      // Sort in memory if we used fallback query
      logs.sort((a, b) => b.contactDate.compareTo(a.contactDate));

      if (kDebugMode) {
        print('✅ [ContactLog] Found ${logs.length} logs for tenant: $tenantId');
      }

      return logs;
    } catch (e) {
      if (kDebugMode) {
        print('❌ [ContactLog] Error getting contact logs: $e');
      }
      rethrow;
    }
  }

  /// Update a contact log
  static Future<void> updateContactLog({
    required String tenantId,
    required String facilityId,
    required String logId,
    String? subject,
    String? message,
    Map<String, dynamic>? metadata,
  }) async {
    try {
      final user = _auth.currentUser;
      if (user == null) throw Exception('User not authenticated');

      if (kDebugMode) {
        print('🔄 [ContactLog] Updating contact log: $logId');
      }

      final updateData = <String, dynamic>{
        'updatedAt': FieldValue.serverTimestamp(),
      };

      if (subject != null) updateData['subject'] = subject;
      if (message != null) updateData['message'] = message;
      if (metadata != null) updateData['metadata'] = metadata;

      await _firestore
          .collection('facilities')
          .doc(facilityId)
          .collection('tenants')
          .doc(tenantId)
          .collection('contactLogs')
          .doc(logId)
          .update(updateData);

      if (kDebugMode) {
        print('✅ [ContactLog] Updated contact log: $logId');
      }
    } catch (e) {
      if (kDebugMode) {
        print('❌ [ContactLog] Error updating contact log: $e');
      }
      rethrow;
    }
  }

  /// Delete a contact log
  static Future<void> deleteContactLog({
    required String tenantId,
    required String facilityId,
    required String logId,
  }) async {
    try {
      final user = _auth.currentUser;
      if (user == null) throw Exception('User not authenticated');

      if (kDebugMode) {
        print('🔄 [ContactLog] Deleting contact log: $logId');
      }

      await _firestore
          .collection('facilities')
          .doc(facilityId)
          .collection('tenants')
          .doc(tenantId)
          .collection('contactLogs')
          .doc(logId)
          .delete();

      if (kDebugMode) {
        print('✅ [ContactLog] Deleted contact log: $logId');
      }
    } catch (e) {
      if (kDebugMode) {
        print('❌ [ContactLog] Error deleting contact log: $e');
      }
      rethrow;
    }
  }
}

