import 'package:cloud_firestore/cloud_firestore.dart';

enum ContactLogType {
  call,
  email,
  sms,
  inPerson,
  note,
  reminder,
  other,
}

enum ContactLogDirection {
  inbound,
  outbound,
}

class ContactLog {
  final String id;
  final String tenantId;
  final String facilityId;
  final ContactLogType type;
  final ContactLogDirection direction;
  final String? subject;
  final String? message;
  final String? contactMethod; // phone number, email address, etc.
  final DateTime contactDate;
  final String contactedBy; // User UID
  final String? contactedByName; // User name for display
  final bool isAutoGenerated; // true if from reminder/automation
  final String? relatedEntityId; // reminderId, paymentId, contractId, etc.
  final String? relatedEntityType; // 'reminder', 'payment', 'contract', etc.
  final Map<String, dynamic>? metadata; // Additional context
  final DateTime createdAt;
  final DateTime? updatedAt;

  const ContactLog({
    required this.id,
    required this.tenantId,
    required this.facilityId,
    required this.type,
    required this.direction,
    this.subject,
    this.message,
    this.contactMethod,
    required this.contactDate,
    required this.contactedBy,
    this.contactedByName,
    this.isAutoGenerated = false,
    this.relatedEntityId,
    this.relatedEntityType,
    this.metadata,
    required this.createdAt,
    this.updatedAt,
  });

  factory ContactLog.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>?;
    if (data == null) {
      throw Exception('ContactLog data is null');
    }

    return ContactLog(
      id: doc.id,
      tenantId: data['tenantId'] ?? '',
      facilityId: data['facilityId'] ?? '',
      type: ContactLogType.values.firstWhere(
        (e) => e.name == data['type'],
        orElse: () => ContactLogType.note,
      ),
      direction: ContactLogDirection.values.firstWhere(
        (e) => e.name == data['direction'],
        orElse: () => ContactLogDirection.outbound,
      ),
      subject: data['subject'],
      message: data['message'],
      contactMethod: data['contactMethod'],
      contactDate: (data['contactDate'] as Timestamp?)?.toDate() ?? DateTime.now(),
      contactedBy: data['contactedBy'] ?? '',
      contactedByName: data['contactedByName'],
      isAutoGenerated: data['isAutoGenerated'] ?? false,
      relatedEntityId: data['relatedEntityId'],
      relatedEntityType: data['relatedEntityType'],
      metadata: data['metadata'] != null
          ? Map<String, dynamic>.from(data['metadata'])
          : null,
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      updatedAt: data['updatedAt'] != null
          ? (data['updatedAt'] as Timestamp).toDate()
          : null,
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'tenantId': tenantId,
      'facilityId': facilityId,
      'type': type.name,
      'direction': direction.name,
      if (subject != null && subject!.isNotEmpty) 'subject': subject,
      if (message != null && message!.isNotEmpty) 'message': message,
      if (contactMethod != null && contactMethod!.isNotEmpty) 'contactMethod': contactMethod,
      'contactDate': Timestamp.fromDate(contactDate),
      'contactedBy': contactedBy,
      if (contactedByName != null && contactedByName!.isNotEmpty) 'contactedByName': contactedByName,
      'isAutoGenerated': isAutoGenerated,
      if (relatedEntityId != null && relatedEntityId!.isNotEmpty) 'relatedEntityId': relatedEntityId,
      if (relatedEntityType != null && relatedEntityType!.isNotEmpty) 'relatedEntityType': relatedEntityType,
      if (metadata != null) 'metadata': metadata,
      'createdAt': Timestamp.fromDate(createdAt),
      if (updatedAt != null) 'updatedAt': Timestamp.fromDate(updatedAt!),
    };
  }

  String get typeDisplayName {
    switch (type) {
      case ContactLogType.call:
        return 'Phone Call';
      case ContactLogType.email:
        return 'Email';
      case ContactLogType.sms:
        return 'SMS';
      case ContactLogType.inPerson:
        return 'In Person';
      case ContactLogType.note:
        return 'Note';
      case ContactLogType.reminder:
        return 'Reminder';
      case ContactLogType.other:
        return 'Other';
    }
  }

  String get directionDisplayName {
    return direction == ContactLogDirection.inbound ? 'Inbound' : 'Outbound';
  }

  ContactLog copyWith({
    String? id,
    String? tenantId,
    String? facilityId,
    ContactLogType? type,
    ContactLogDirection? direction,
    String? subject,
    String? message,
    String? contactMethod,
    DateTime? contactDate,
    String? contactedBy,
    String? contactedByName,
    bool? isAutoGenerated,
    String? relatedEntityId,
    String? relatedEntityType,
    Map<String, dynamic>? metadata,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return ContactLog(
      id: id ?? this.id,
      tenantId: tenantId ?? this.tenantId,
      facilityId: facilityId ?? this.facilityId,
      type: type ?? this.type,
      direction: direction ?? this.direction,
      subject: subject ?? this.subject,
      message: message ?? this.message,
      contactMethod: contactMethod ?? this.contactMethod,
      contactDate: contactDate ?? this.contactDate,
      contactedBy: contactedBy ?? this.contactedBy,
      contactedByName: contactedByName ?? this.contactedByName,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      relatedEntityId: relatedEntityId ?? this.relatedEntityId,
      relatedEntityType: relatedEntityType ?? this.relatedEntityType,
      metadata: metadata ?? this.metadata,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}

