// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'This app currently only supports web platform. '
          'Android, iOS, macOS, Windows, and Linux support will be added later.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4VshUYPFyQSUIBvfjPZJ3VeRRXim5Cjo',
    appId: '1:255655613485:web:d4a3488682e7fccc0bd4a4',
    messagingSenderId: '255655613485',
    projectId: 'storage-facility-creator',
    authDomain: 'storage-facility-creator.firebaseapp.com',
    storageBucket: 'storage-facility-creator.appspot.com',
  );

  // Android, iOS, macOS, and Windows configurations will be added later
  // when we need to support those platforms
}
